-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwptr6cH5OHm3Embn
7m61mI9GjZubhtBn2nEqShR8FV2gCgYIKoZIzj0DAQehRANCAATzyvmovfoQEswf
F/RRliKknjzkHwA+OGJlokP5AZsk7N0UwYtOaysyQOKwb4kpoGVGdi93bzOAKs4W
VxRnELmz
-----END PRIVATE KEY-----